Feat/Add product-page-mobile
alekseevgeorgy/fake-burberry-frontend pull request #1
Opened 2017-08-01 08:38 UTC by alekseevgeorgy

2017-08-01 12:14 UTC, evgenyrodionov commented
https://rawgit.com/alekseevgeorgy/fake-burrberry-frontend/feat/product-page/product.html

![image](https://user-images.githubusercontent.com/775692/28824707-010cdadc-76cc-11e7-8fb6-8d1a0849ec9d.png)
![image](https://user-images.githubusercontent.com/775692/28824710-0a9d118e-76cc-11e7-94b7-ec65d2e7e408.png)
![image](https://user-images.githubusercontent.com/775692/28824717-132340da-76cc-11e7-84d8-2357808f8c12.png)
![image](https://user-images.githubusercontent.com/775692/28824722-19d26e88-76cc-11e7-8ccb-0651b86b1518.png)
![image](https://user-images.githubusercontent.com/775692/28824728-213a5e60-76cc-11e7-9ec7-67eb38a4d941.png)

2017-08-01 12:15 UTC, imevro requested changes
фикси дизайн

2017-08-01 20:45 UTC, alekseevgeorgy commented
- починил дизайн, поменял где нужно под новый макет
- текст в описании сделал отдельными параграфами
- еще поменял карточки в рекомендациях — теперь это один флекс-контейнер с карточками, который двигает их на следующую строку

2017-08-01 21:33 UTC, evgenyrodionov commented
Единственно возможный приёб это в футере мыло 

![image](https://user-images.githubusercontent.com/775692/28848048-25a0ab64-771a-11e7-9d35-697b3be21d87.png)

2017-08-01 21:36 UTC, imevro requested changes
очень-очень хорошо

2017-08-01 21:36 UTC, evgenyrodionov commented on product.html
> +            110 000 руб
поставь точку

2017-08-01 21:36 UTC, evgenyrodionov commented on product.html
> +          <!-- <img class="product-info-arrow" src="img/triangle-down.svg" /> -->
лучше иметь 1 файл и поворачивать его через цсс

2017-08-01 21:36 UTC, evgenyrodionov commented on product.html
> +      <button class="button-footer">Shipping country: Russian Federation</button>
от общего к частному, а не наоборот

2017-08-01 21:36 UTC, evgenyrodionov commented on css/style.css
> +.product-description-color-button-wrapper {
color

2017-08-01 21:36 UTC, evgenyrodionov commented on css/style.css
> +.button-product-description-colour {
colour

2017-08-01 21:36 UTC, evgenyrodionov commented on css/style.css
> +.button-product-description-colour {
плюс colour что?

2017-08-01 21:36 UTC, evgenyrodionov commented on css/style.css
> +.button-product-description-colour {
это же кнопка

2017-08-01 21:36 UTC, evgenyrodionov commented on css/style.css
> +.product-description {
это инфо, не дескрипшен

2017-08-01 21:36 UTC, evgenyrodionov commented on css/style.css
> +.product-name-title {
name-title?

2017-08-01 21:44 UTC, imevro requested changes

2017-08-01 21:44 UTC, evgenyrodionov commented on product.html
> +<html lang="ru">
en

2017-08-01 21:52 UTC, imevro requested changes

2017-08-01 21:52 UTC, evgenyrodionov commented on product.html
> +          <div class="product-recommendations-card">
почему не ссылкой

2017-08-01 21:52 UTC, evgenyrodionov commented on product.html
> +          <button class="button-product-description-colour button-bg-black"></button>
если не указывать type у кнопки, то она попробует отправить форму, а это не совсем то что тебе нужно

2017-08-02 10:43 UTC, evgenyrodionov commented
Почему у логотипа бордер? 

![image](https://user-images.githubusercontent.com/775692/28870261-431f7652-7788-11e7-9b91-b5f2ed1c64d5.png)
![image](https://user-images.githubusercontent.com/775692/28870287-5b4f7cb8-7788-11e7-8e9a-e8d2605b93fe.png)
![image](https://user-images.githubusercontent.com/775692/28870310-77b6dc0c-7788-11e7-92fd-c716e73330ba.png)

2017-08-02 10:43 UTC, imevro requested changes
↑

2017-08-02 16:49 UTC, alekseevgeorgy commented
Несовпадения с макетом:
1) Бордер, который находится между SHIPPING & RETURNS и текстом описания — про это говорили в чате, баг (?) хрома. Чтобы нижний бордер у SHIPPING & RETURNS совпадал, сделал класс product-description-heading-lineheight-fix, в котором выставил line-height в 19px.
2) В футере у обоих кнопок стоит line-height 16px, не как в макете 14px у второй — ты написал в чате так сделать.
3) Гозиронтально некоторые буквы едут из-за рендеринга

2017-08-02 19:08 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28890200-0375307c-77cf-11e7-82ed-f0838e013346.png)

2017-08-02 19:10 UTC, imevro requested changes

2017-08-02 19:10 UTC, evgenyrodionov commented on product.html
> +          <p class="product-description-text">Buttons: buffalo horn</p>
это список

2017-08-02 19:10 UTC, evgenyrodionov commented on product.html
> +          <p class="product-description-text">The piece is finished with a distinctive check undercollar.</p><br class="product-description-text-break"/>
с сервера приходит чистый хтмл без классов

2017-08-02 19:10 UTC, evgenyrodionov commented on product.html
> +      <div class="product-name">
а есть необходимость дива вокруг h1?

2017-08-02 19:10 UTC, evgenyrodionov commented on product.html
> +    <link rel="icon" type="image/png" href="img/favicon.ico">
тип не совпадает

2017-08-02 22:04 UTC, imevro approved these changes

2017-08-02 22:04 UTC, evgenyrodionov commented on product.html
> +          <!-- <p>Outer: 100% cotton</p>
снеси закомментироанный код

2017-08-04 21:03 UTC, alekseevgeorgy commented
1) Сразу скажу, что забыл сделать height: 100% для фоток товара в первом блоке. Сделаю.
2) Треугольник в шиппинг на 1 пиксель съехал, потому что там эта хуйня с line-height багом и тд. Если нужно — я знаю как это исправить (задать точный паддинг треугольнику , например), но это + 1 класс и свойство. Ну и вроде мы обсудили, что такой пиксель перфект не нужен.

2017-08-04 21:09 UTC, imevro approved these changes

2017-08-04 21:10 UTC, merged