Feat/product page react implement
alekseevgeorgy/fake-burberry-frontend pull request #2
Opened 2017-08-10 16:08 UTC by alekseevgeorgy

2017-08-10 17:25 UTC, imevro requested changes

2017-08-10 17:25 UTC, evgenyrodionov commented on public/index.html
> +    <title>Long Cotton Gabardine Car Coat | Men - Burberry</title>
react-helmet

2017-08-10 17:25 UTC, evgenyrodionov commented on public/index.html
> +    <!-- <link rel="stylesheet" href="https://unpkg.com/flexboxgrid2"> -->
мусор

2017-08-10 17:25 UTC, evgenyrodionov commented on src/App.css
> +.App {
тоже мусор

2017-08-10 17:25 UTC, evgenyrodionov commented on src/App.js
> +class App extends Component {
зачем класс

2017-08-10 17:25 UTC, evgenyrodionov commented on src/Product/Description/Button.jsx
> +      <Triangle src={triangle} />
как-то не очень круто срать таким в разметку и заводить отдельный элемент аж

2017-08-10 17:25 UTC, evgenyrodionov commented on src/Product/Info/Colour.jsx
> +      <Button bg="#232122" />
bg? это не имеет отношения к бизнес-логике

2017-08-10 17:25 UTC, evgenyrodionov commented on src/Product/Info/Colour.jsx
> +      <Button bg="#232122" />
color более близко

2017-08-10 17:25 UTC, evgenyrodionov commented on src/Product/Info/Images.jsx
> +        alt={"product-photo-4"}
можно обойтись обычной строкой, не нужно {}

2017-08-10 17:25 UTC, evgenyrodionov commented on src/Product/Info/Name.jsx
> +    Long Cotton Gabardine Car Coat
ты серьезно думаешь что это стоило делать? что мешает сразу экспортнуть стайлед-компонент и заюзать его?

2017-08-10 20:12 UTC, alekseevgeorgy commented on src/Product/Info/Name.jsx
> +    Long Cotton Gabardine Car Coat
хз, думал, что если мы будем передавать название через пропсы, то под название стоит завести отдельный компонент

2017-08-10 22:27 UTC, evgenyrodionov commented on package.json
> +    "flexboxgrid2": "^7.0.0-alpha6",
ого, первый релиз и уже взрослый как нормалайз!

2017-08-10 22:29 UTC, imevro requested changes

2017-08-10 22:29 UTC, evgenyrodionov commented on src/Product/Recommends/index.jsx
> +          image={
а тут почему не убрал джс-пропы?

2017-08-10 22:29 UTC, evgenyrodionov commented on src/Product/Recommends/index.jsx
> +          price={"120 000 руб"}
числом передавай, а не строкой

2017-08-10 22:29 UTC, evgenyrodionov commented on src/Product/Shipping.jsx
> +        <TextBold>Free Gift Packaging</TextBold>
это заголовок, а не текстболд

2017-08-11 02:17 UTC, alekseevgeorgy commented
Добавил react-intl, теперь цены по царски отображаются в зависимости от указанного locale в index.js. Этот праздник стоил мне почти целой ночи, но как же это круто. Все остальное, разумеется, тоже пофиксил.

2017-08-11 10:42 UTC, imevro requested changes

2017-08-11 10:42 UTC, evgenyrodionov commented on src/Product/Info/Cta.jsx
> +      <Button colour="#171717" textColour="#fff">
делай лучше primary / secondary

2017-08-11 10:42 UTC, evgenyrodionov commented on src/Product/Info/Price.jsx
> +    <Article>
это не статья, это айди

2017-08-11 10:42 UTC, evgenyrodionov commented on src/Product/Recommends/index.jsx
>            name={"Emroided Hooded Content For Three Lines"}
так и что

2017-08-12 11:04 UTC, imevro requested changes

2017-08-12 11:04 UTC, evgenyrodionov commented on src/Product/Description/index.jsx
> +var MediaQuery = require("react-responsive");
почему не импортом?

2017-08-12 11:04 UTC, evgenyrodionov commented on src/Product/Description/index.jsx
> +    margin-bottom: 4rem;
лучше весь блок-роу в марджин боттом закатать

2017-08-12 11:04 UTC, evgenyrodionov commented on src/Product/Description/index.jsx
> +const Wrapper = styled.div`
плохой нейминг, сделай Images или что-то в этом духе

2017-08-12 11:04 UTC, evgenyrodionov commented on src/Product/Info/Colour.jsx
> +  @media screen and (min-width: 768px) {
почему не в ремах

2017-08-12 11:04 UTC, evgenyrodionov commented on src/Product/Info/Cta.jsx
> +      <ButtonHelp>NEED SIZE HELP?</ButtonHelp>
а тут-то зачем реакт-респонсив?

2017-08-12 11:04 UTC, evgenyrodionov commented on src/Product/Recommends/index.jsx
> +            image={
ЖОРА ПЕРЕДЕЛАЙ НА СТРОКУ ОБЫЧНУЮ ГОВОРИЛ СОТНЮ РАЗ

2017-08-12 17:55 UTC, imevro approved these changes
вроде ок

2017-08-13 13:52 UTC, merged