Feat/products page
alekseevgeorgy/fake-burberry-frontend pull request #4
Opened 2017-08-18 04:18 UTC by alekseevgeorgy

Жень, там в компоненте Card.jsx есть проп productStyle — сделал префикс, потому что style называть нельзя.

2017-08-18 16:00 UTC, alekseevgeorgy commented
https://fake-burberry-frontend-vuwccdjqin.now.sh/

2017-08-18 16:14 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29467474-60ab727a-8449-11e7-83f5-4f4c5ff34b18.png)
![image](https://user-images.githubusercontent.com/775692/29467487-6c1db488-8449-11e7-8f60-ef45e64da452.png)

2017-08-18 16:15 UTC, evgenyrodionov commented
Вот здесь просто отступ от заголовка до цены

![image](https://user-images.githubusercontent.com/775692/29467506-7aad6976-8449-11e7-84b8-d74ed1b6431b.png)

2017-08-18 16:16 UTC, evgenyrodionov commented
По поводу деплоя — нужно деплоить не через `now sh`, потому что тогда стартует вебпак-сервер (из-за `start`), нужно деплоить директорию `build`

2017-08-18 16:24 UTC, imevro requested changes

2017-08-18 16:24 UTC, evgenyrodionov commented on src/App.jsx
> +        <Route exact path="/product" component={Product} />
написал в телеграф про ссылки

2017-08-18 16:24 UTC, evgenyrodionov commented on src/List/Filter/Filter.jsx
> +  Button:last-child {
дело не в ластчайлде раз
обращаться к компонентам нужно не так два

2017-08-19 03:10 UTC, alekseevgeorgy commented
Все поправил, про хедер писал в чат, у react-responsive нет эвент ресайза, поэтому то, что ты показал на скрине выше уйдет при релоаде страницы.
Новый деплой https://build-lsborsdepi.now.sh/

2017-08-19 09:30 UTC, evgenyrodionov commented
Можешь поправить этот отступ?

![image](https://user-images.githubusercontent.com/775692/29485396-fc85d394-84d9-11e7-892b-bc17218e0b41.png)

Поправь футер

![image](https://user-images.githubusercontent.com/775692/29485401-0d865646-84da-11e7-9509-3854899912e7.png)

2017-08-19 09:31 UTC, evgenyrodionov commented
Планшет

![image](https://user-images.githubusercontent.com/775692/29485410-28cc9686-84da-11e7-93f8-dd836f61de77.png)
![image](https://user-images.githubusercontent.com/775692/29485417-3abe466e-84da-11e7-820d-aea978dffd5b.png)
![image](https://user-images.githubusercontent.com/775692/29485418-41b13e4a-84da-11e7-9561-a4bdf29184e7.png)

2017-08-19 09:32 UTC, evgenyrodionov commented
Десктоп
![image](https://user-images.githubusercontent.com/775692/29485426-6024448a-84da-11e7-8f65-d4442ec1f3df.png)
![image](https://user-images.githubusercontent.com/775692/29485430-6efe6ff8-84da-11e7-96d8-7dc7617d9a66.png)
![image](https://user-images.githubusercontent.com/775692/29485432-78ca70fe-84da-11e7-9710-256ee3049001.png)

2017-08-19 12:56 UTC, alekseevgeorgy commented
В футере у картинки Find Store белые полоски, потому что таких пропорций как в макете нет на сайте, чтобы сошлось, дал картинке размеры из макета и поэтому появились полосы.

2017-08-19 13:38 UTC, evgenyrodionov commented
Где тайтл
![image](https://user-images.githubusercontent.com/775692/29487096-d29678fe-84fc-11e7-9605-aab64f3228d9.png)

2017-08-19 13:39 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29487098-df7494ca-84fc-11e7-8790-2925a63da98c.png)
![image](https://user-images.githubusercontent.com/775692/29487102-ea1c4f08-84fc-11e7-80de-343a41cdc40b.png)

2017-08-19 13:40 UTC, evgenyrodionov commented
Пикчи артефактные на ретине, бери х2 размер всегда

![image](https://user-images.githubusercontent.com/775692/29487110-f866c174-84fc-11e7-846b-1bef177f0a55.png)

2017-08-19 13:40 UTC, evgenyrodionov commented
Можешь заменить карточки?

![image](https://user-images.githubusercontent.com/775692/29487116-1463a450-84fd-11e7-8420-ec01afd15777.png)

2017-08-19 13:41 UTC, evgenyrodionov commented
Пикча отвалилась, почитай телеграф про паблик урл

![image](https://user-images.githubusercontent.com/775692/29487121-2578340e-84fd-11e7-9733-2c433ff84de0.png)

Клик не работает
![image](https://user-images.githubusercontent.com/775692/29487126-2cd7fb62-84fd-11e7-8bf7-53bad477c0a8.png)

2017-08-19 13:41 UTC, evgenyrodionov commented
На иконку сердца нельзя нажать — кидает на страницу товара

2017-08-19 13:42 UTC, evgenyrodionov commented
С сеткой что-то не то

![image](https://user-images.githubusercontent.com/775692/29487134-4a77ca76-84fd-11e7-92a0-64f2c47663ba.png)

Тут РУБ, а в остальных местах нормальное ₽
![image](https://user-images.githubusercontent.com/775692/29487141-5c0b7ba2-84fd-11e7-9dd6-b5ce24429896.png)

2017-08-19 13:48 UTC, imevro requested changes

2017-08-19 13:48 UTC, evgenyrodionov commented on src/App.jsx
> +import List from './List';
лист чего? вот в футере у тебя есть Our Company → Careers, этот компонент отвечает за этот лист?

2017-08-19 13:48 UTC, evgenyrodionov commented on src/Footer/Preferences.jsx
> +const BlackColour = Button.extend`
кнопка в кнопке?

2017-08-19 13:48 UTC, evgenyrodionov commented on src/Header/Header.jsx
> +    background: url(${arrow}) 0 0 no-repeat;
иконка принадлежит `United Kingdom (£)`

2017-08-19 13:48 UTC, evgenyrodionov commented on src/Header/Subheader.jsx
> +    <Button selected>MEN</Button>
почему это кнопка?

2017-08-19 13:48 UTC, evgenyrodionov commented on src/Header/Subheader.jsx
> +    <Button selected>MEN</Button>
почему не https://reacttraining.com/react-router/web/api/NavLink ?

2017-08-19 13:48 UTC, evgenyrodionov commented on src/List/Filter/Filter.jsx
> +    <Button alignRight>Sort by price</Button>
если добавлю кнопку справа, что будет?

2017-08-19 13:48 UTC, evgenyrodionov commented on src/List/Filter/index.jsx
> +const TextLink = styled.a`
почему не через роутер?

2017-08-19 13:48 UTC, evgenyrodionov commented on src/Product/Info/Images.jsx
> +    <Image src={`${process.env.PUBLIC_URL}/img/product-photo-1.png`} alt="product-photo-1" />
почему бы не брать эти пикчи с сайта берберри?

2017-08-19 17:31 UTC, alekseevgeorgy commented on src/List/Filter/Filter.jsx
> +    <Button alignRight>Sort by price</Button>
переделал, распишу логику в следующем пр

2017-08-19 17:39 UTC, alekseevgeorgy commented on src/Product/Info/Images.jsx
> +    <Image src={`${process.env.PUBLIC_URL}/img/product-photo-1.png`} alt="product-photo-1" />
потому что нашего пальто больше нет на сайте, а ссылки на картинки я сохранить не успел, в чате спросил — у всех тоже локально вроде. если найду ссылки — поменяю

2017-08-19 20:56 UTC, alekseevgeorgy commented
Поправил все, что ты писал тут, но кое что должен расписать.

- Картинки в описании (компонент `src/Product/Info/Images.jsx`) я не могу поменять на ссылки, потому что нашего пальто больше нет на сайте, а ссылки на картинки я сохранить не успел, в чате спросил — у всех тоже локально вроде. если найду ссылки — поменяю
- В компоненте `src/List/Filter/Filter.jsx` сделал так, что если нужно будет добавить еще кнопок, которые будут прибиты к правому краю, то это можно сделать, обернув кнопку в новый компонент `<ButtonRight>`. При ширине 768 и больше такие кнопки прибиваются к правому краю, а до этой ширины кнопки идут друг за другом (только нужно использовать обычный компонент`<Button>`)
- Кое-где не совпадают размеры картинок — это потому что описание местами теперь занимает 3 строчки, тк кнопка favourite имеет свой left-margin. Но вообще все должно быть ок.

2017-08-19 21:44 UTC, evgenyrodionov commented
Ты заменил карточки?
![image](https://user-images.githubusercontent.com/775692/29490294-9858b1ea-8540-11e7-8307-7a5a4105315e.png)

2017-08-19 21:47 UTC, imevro requested changes
а в целом ок

2017-08-19 21:47 UTC, evgenyrodionov commented on src/App.jsx
> +import ProductsList from './ProductsList';
Если ты работаешь с бизнес-сущностью товаров, что мешает завести `Products/List` и `Products/Show`? Ну или `Products/View`?

2017-08-19 21:47 UTC, evgenyrodionov commented on src/Header/Subheader.jsx
> +    <Button to="/men/" selected>
https://reacttraining.com/react-router/web/api/NavLink

2017-08-19 21:47 UTC, evgenyrodionov commented on src/ProductsList/Filter/Filter.jsx
> +        <ButtonRight>Sort by price</ButtonRight>
не нравится что ты дублируешь контент, можешь без этого обойтись?

2017-08-19 23:50 UTC, alekseevgeorgy commented
Все поправил, про карточки затупил, думал, там фотки новые нужны, лол.

Новый деплой https://build-iittmewpkh.now.sh

2017-08-20 09:33 UTC, imevro approved these changes

2017-08-20 09:33 UTC, merged